### ISSUE TITLE
Random noise during conversion

### ISSUE THREAD

**Issue by aguzman7338** [gavinbeatty/mkvtomp4#14]
This program makes a random popping noise during conversion with no way of disabling it. It's really loud and annoying and I can't go into volume mixer to disable it because it only lasts for half a second before the sound stops and disappears from volume mixer.

**Comment by gavinbeatty** [comment]
Sorry about that, @aguzman7338. I have no way to reproduce, but the issue is almost certainly caused by the underlying tools themselves.

I suggest:
* Running mkvtomp4.py in --dry-run mode
* Running each of the commands separately, with a pause/sleep in between

That way you might be able to determine which tool is the cause. If you can only reproduce by running mkvtomp4.py, let me know.
