### ISSUE TITLE
Not sure if I am stupid or...

### ISSUE THREAD

**Issue by VirgilFabre** [gavinbeatty/mkvtomp4#16]
![start](https://user-images.githubusercontent.com/40531871/81646978-3f389000-93fa-11ea-9c9f-44aea2010f39.png)
![file](https://user-images.githubusercontent.com/40531871/81647014-537c8d00-93fa-11ea-82b0-05f8ee1b39c8.png)
![cmd](https://user-images.githubusercontent.com/40531871/81647057-642d0300-93fa-11ea-8320-7792bdbf521c.png)
I also tried without the extension...
I'm confused

**Comment by gavinbeatty** [comment]
The error message is unclear, but it's unable to run the mkvinfo executable because it's not found. From the README:

Dependencies
------------

Tools:

* *mkvtoolnix*
* GPAC's *MP4Box*
* *ffmpeg* (optional, for audio encoding and subtitles)

To install these tools:

* On Linux, use your package manager.
* On Mac OS X, use MacPorts or homebrew.
* On Windows, go to each tools' individual websites.

If you already have it installed, and it's not in your PATH for some reason, you can supply the full path with --mkvinfo=thepath.

I made the error more clear in 3095bd6f05282e44b526105be46fcbad7312e10d, just pushed.
